language: php

sudo: false

php:
  - 7.4

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs .
  - vendor/bin/psalm --show-info=false
  - ./check-refs-readmes
