name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

    - uses: php-actions/phpunit@v1
    
    - name: phpcs
      run: vendor/bin/phpcs .
    
    - name: psalm
      run: vendor/bin/psalm --show-info=false
      
    - name: check readme refs
      run: ./check-refs-readmes
